SQL-1126: Use odbc snapshot instead of building

diff --git a/evergreen.yml b/evergreen.yml
--- a/evergreen.yml
+++ b/evergreen.yml
@@ -65,10 +65,6 @@ functions:
         shell: bash
         working_dir: mongo-powerbi-connector
         script: |
-          export CARGO_NET_GIT_FETCH_WITH_CLI=true
-          export UNIX_ODBC_PATH="$PWD/unixodbc/install"
-          export LD_LIBRARY_PATH="$UNIX_ODBC_PATH/lib"
-          export PATH="$LD_LIBRARY_PATH:$PATH:$HOME/.cargo/bin"
           export MONGO_POWERBI_CONNECTOR_VERSION=$(git describe --always | sed 's/^v//g')
           export UPDATE_PLUGIN_VERSION=true
           git describe --exact-match HEAD || UPDATE_PLUGIN_VERSION=false
@@ -86,8 +82,6 @@ functions:
             export ADF_TEST_LOCAL_AUTH_DB="${adf_test_local_auth_db}"
             export ADF_TEST_LOCAL_HOST="${adf_test_local_host}"
             export MDB_TEST_LOCAL_PORT="${mdb_test_local_port}"
-            export PATH="$PATH"
-            export CARGO_NET_GIT_FETCH_WITH_CLI="$CARGO_NET_GIT_FETCH_WITH_CLI"
           EOT
     - command: expansions.update
       params:
@@ -117,43 +111,9 @@ functions:
           unzip -n tools.zip
           chmod -R +x tools/*
 
-  "install rust toolchain":
-    - command: shell.exec
-      params:
-        shell: bash
-        script: |
-          ${prepare_shell}
-          # make sure to use msvc toolchain rather than gnu, which is
-          # the default for cygwin
-          if [ "Windows_NT" == "$OS" ]; then
-              if [ 'windows-64' == '${build_variant}' ]; then
-                  export HOST="x86_64-pc-windows-msvc"
-              else
-                  echo 'unknown windows build variant ${build_variant}'
-                  exit 1;
-              fi
-              export DEFAULT_HOST_OPTIONS="--default-host $HOST"
-              export DEFAULT_TOOLCHAIN="stable-$HOST"
-          fi
-          # install rustup from scratch
-          rm -rf ~/.rustup
-          curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path $DEFAULT_HOST_OPTIONS
-          # rustup installs into C:\Users\$USER instead of
-          # C:\home\$USER, so we symlink both .rustup and .cargo
-          if [ "Windows_NT" == "$OS" ]; then
-              ln -sf /cygdrive/c/Users/$USER/.rustup/ ~/.rustup
-              ln -sf /cygdrive/c/Users/$USER/.cargo/ ~/.cargo
-              rustup toolchain install $DEFAULT_TOOLCHAIN
-              rustup default $DEFAULT_TOOLCHAIN
-          fi
-          echo --------- rustup show -----------
-          rustup show
-          echo ----- Rustup toolchain list -----
-          rustup toolchain list
-          echo ---------------------------------
-
   "run integration test":
     - command: shell.exec
+      type: test
       params:
         add_expansions_to_env: true
         shell: bash
@@ -188,14 +148,17 @@ functions:
           
           # Run Integration Test
           test_output=`tools/PQTest.exe run-test --extension MongoDBAtlasODBC.pqx \
-            --queryFile connector/MongoDBAtlasODBC.integration-test.query.pq`
+            --queryFile connector/MongoDBAtlasODBC.integration-test.query.pq --prettyPrint`
           EXITCODE=$?
-          failures=`echo $test_output  | grep -Eo '"Result"[^}]*' | grep Failure || true` 
+          echo "$test_output"
+          failures=`echo "$test_output"  | grep Failure -A 1 || true` 
           echo $test_output > MongoDBAtlasODBC.integration-test.log 
           if [[ ! -z $failures ]]; then 
             echo "Failures Encountered:"
             echo $failures
-            exit 1
+            if [ "$EXITCODE" -eq "0" ]; then
+              EXITCODE=1
+            fi
           fi
           
           # Stop local ADF, always run this to keep task from hanging
@@ -204,14 +167,16 @@ functions:
 
   "run unit-test":
     - command: shell.exec
+      type: test
       params:
         shell: bash
         working_dir: mongo-powerbi-connector
         script: |
           ${prepare_shell}
           test_output=`tools/PQTest.exe run-test --extension MongoDBAtlasODBC.pqx \
-          --queryFile connector/MongoDBAtlasODBC.unit-test.query.pq` 
-          failures=`echo $test_output  | grep -Eo '"Result"[^}]*' | grep Failure || true` 
+          --queryFile connector/MongoDBAtlasODBC.unit-test.query.pq --prettyPrint` 
+          echo "$test_output"
+          failures=`echo "$test_output"  | grep Failure -A 1 || true` 
           echo $test_output > MongoDBAtlasODBC.unit-test.log 
           if [[ ! -z $failures ]]; then 
             echo "Failures Encountered:"
@@ -219,19 +184,17 @@ functions:
             exit 1
           fi
 
-  "setup driver on Windows":
+  "setup ODBC driver on Windows":
     - command: shell.exec
       params:
         shell: bash
         working_dir: mongo-powerbi-connector
         script: |
           ${prepare_shell}
-          git clone git@github.com:mongodb/mongo-odbc-driver.git
-          cd mongo-odbc-driver
-          cargo build --release
-          cp target/release/mongoodbc.dll ./mongoodbc.dll
-          sed -i 's@%DRIVER_DLL_PATH%@'"$(echo "$(cygpath -w $(pwd))" | sed s',\\,\\\\\\\\,g')"'@' setup/setupDSN.reg
-          reg import "setup\setupDSN.reg"
+          curl -O https://translators-connectors-releases.s3.us-east-1.amazonaws.com/mongosql-odbc-driver/windows/snapshot/mongoodbc.dll
+          chmod 777 ./mongoodbc.dll
+          sed -i 's@%DRIVER_DLL_PATH%@'"$(echo "$(cygpath -w $(pwd))" | sed s',\\,\\\\\\\\,g')"'@' resources/odbc/setupDSN.reg
+          reg import "resources\odbc\setupDSN.reg"
           echo "----- Registry entries after setup ----"
           reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\ODBC\ODBCINST.INI\ODBC Drivers" -s 2> /dev/null || true
           reg query "HKEY_LOCAL_MACHINE\SOFTWARE\ODBC\ODBCINST.INI\ODBC Drivers" -s 2> /dev/null || true
@@ -239,15 +202,14 @@ functions:
           reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\ODBC\ODBCINST.INI\ADF_ODBC_DRIVER" -s 2> /dev/null || true
           echo "-------------------------"
 
-  "clean up driver on Windows":
+  "clean up ODBC driver on Windows":
     - command: shell.exec
       params:
         shell: bash
         working_dir: mongo-powerbi-connector
         script:  |
           ${prepare_shell}
-          cd mongo-odbc-driver
-          reg import "setup\cleanup_driver.reg"
+          reg import "resources\odbc\cleanup_driver.reg"
           echo "----- Registry entries after clean-up----"
           reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\ODBC\ODBCINST.INI\ODBC Drivers" -s 2> /dev/null || true
           reg query "HKEY_LOCAL_MACHINE\SOFTWARE\ODBC\ODBCINST.INI\ODBC Drivers" -s 2> /dev/null || true
@@ -327,7 +289,7 @@ pre:
   - func: "install power query tools"
 post: 
   - func: "upload unit test logs"
-  - func: "upload integration test logs"
+
 
 tasks:
   - name: build
@@ -339,12 +301,8 @@ tasks:
     depends_on:
       - name: build
     commands:
-      - func: "install rust toolchain"
-      - func: "setup driver on Windows"
-      - func: "fetch packaged connector"
       - func: "install mongoimport tool"
       - func: "run integration test"
-      - func: "clean up driver on Windows"
 
   - name: unit-test
     depends_on:
@@ -370,6 +328,21 @@ tasks:
       - func: "fetch signed connector"
       - func: "upload release"
 
+task_groups:
+  - name: test-integration-group
+    setup_group_can_fail_task: true
+    setup_group:
+      - func: "fetch powerbi source"
+      - func: "generate expansions"
+      - func: "fetch packaged connector"
+      - func: "install power query tools"
+      - func: "setup ODBC driver on Windows"
+    teardown_group:
+      - func: "clean up ODBC driver on Windows"
+      - func: "upload integration test logs"
+    tasks:
+      - integration-test
+
 buildvariants:
   - name: windows-64
     display_name: "Windows"
@@ -377,6 +350,6 @@ buildvariants:
     tasks:
       - name: build
       - name: unit-test
-      - name: integration-test
+      - name: test-integration-group
       - name: sign
       - name: release
